name: Build and Test

on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]  

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet Packages
      run: msbuild /t:restore Client/Client.sln

    - name: Build Solution
      run: |
        msbuild Client/Client.sln /p:Configuration=Release /p:Platform=x64 /p:AdditionalDependencies="ntdll.lib"
        dir ./Client/Release /b /s *.exe

    - name: Run Tests
      run: msbuild /t:VSTest Client/Client.sln
